name: build

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - master
      - 'feature/*'
      - 'bugfix/*'
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Build nvm-base, test it, create some node images
        run: |
          # build base/nvm
          docker build \
            --tag tgagor/base/nvm base-nvm

      - name: Build node:16 and node:18
        run: |
          # build node v16
          docker build \
            --build-arg NODE_VERSION=16 \
            --tag tgagor/base/node:16 node

          # build node v18
          docker build \
            --build-arg NODE_VERSION=18 \
            --tag tgagor/base/node:18 node
      - name: Test it
        run: |
          set -x
          docker run -i tgagor/base/node:16 node --version
          docker run -i tgagor/base/node:18 node --version

          docker build \
            --tag tgagor/base/nvm-tests tests
