name: build

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - master
      - 'feature/*'
      - 'bugfix/*'
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Build nvm-base
        run: |
          make build-base
          make list

      - name: Build node:18
        run: |
          make build-node
          make list

      - name: Test it
        run: |
          make test
